### PR TITLE
Update amethyst dependency & bump version

### PR DESCRIPTION
**Pull request by ghost**
I don't think there were any breaking changes to the interfaces `amethyst_physics` uses in `amethyst_core` 0.9 or 0.10, so I think this can just be a version bump.

If the version bump is inappropriate, I can remove that change and just have this be a dependency update.

My testing consists of running https://github.com/AndreaCatania/amethyst_physics_test with the updated amethyst, amethyst_physics and amethyst_nphysics. It appears to run well!

Thanks for making this library!

### CODE REVIEW

**Comment by AndreaCatania** [comment]
Can you please set version `0.1.2` instead of `0.2.0` ?

**Comment by ghost** [comment]
If you want, I can do that! But I would rather not, since it would break existing users of `amethyst_physics`.

`cargo` and the rust ecosystem strongly assume that all crates with the same major version are backwards-compatible. But since this upgrades amethyst's major version, I don't think it is backwards compatible.

I am imagining some downstream user who uses both `amethyst` 0.13 and `amethyst_physics` 0.1.1. If `amethyst_physics` 0.1.2 is released, and they do `cargo update`,  then this downstream user's code will break and they won't be able to compile until they also update amethyst. We would force them to update.

If instead, it's called `amethyst_physics` 0.2.0, then the downstream user can choose to not upgrade either until they want to upgrade both.

I believe this is the principle most of the rust ecosystem follows: if you update a to a new major version of a dependency, then you must also release a new major version (and to do otherwise breaks `cargo`'s assumptions). It's always assumed that `cargo update` won't break your code.

**Comment by AndreaCatania** [comment]
Yes you are correct. Sletp my mind about that all 0.1.x would automatically update to new version. It looks nice, thanks!

**Comment by ghost** [comment]
Glad to help. Thanks for writing and maintaining this!

**Pull request merged**
